### ISSUE TITLE
Classification and the open world assumption

### ISSUE THREAD

**Issue by knutasm** [KGConf/Bookclub-DemystifyingOWL#15]
So I understand that we can classify individuals based on a defined class that is equivalent to the intersection of a set of (potentially anonymous) classes, and that those classes can be the set of all individuals that are subject to some property/properties. But what if I want to classify individuals that are not subject to a specific property? 

Examle:
Let's say I want to talk about companies, and I want to say that any company that does not have a parent company, is an ultimate parent company (by extension being the ultimate parent of itself).  So, if the individual is not subject to a hasParentCompany relation to another company, then it is classified accordingly. However, in light of the owa, the absence of this triple in my fact set does not equate to it being false, as I understand it. Is it possible to perform such a classification? Would I have to make explicit the fact that the entity does not have a parent?

**Comment by uscholdm** [comment]
> But what if I want to classify individuals that are not subject to a specific property?

I took this to mean you want to classify individuals in the case when there is nothing to do with any property.  There is a way to do that using set operations, but it seems instead you mean that you want to classify an individual if it is KNOWN that there is no triple with it as the subject using a particular property.   

> However, in light of the owa, the absence of this triple in my fact set does not equate to it being false, as I understand it.

That is correct.  

> Would I have to make explicit the fact that the entity does not have a parent?

I know of no way to do that. You can do something similar using the set complement operator which we cover in chapter 5.  It would be something like this:
1. define a class that is `equivalentTo` the restriction `(hasParentCompany min 1)`. Call it `CompanyWithParent`.
2. define a class that is `equivalentTo` the complement of `CompanyWithParent` and call it `CompanyWithoutParent`
3. assert an individual to be in the `CompanyWithoutParent` class.


From this you can infer that the individual has no `hasParentCompany` property, but you cannot do that directly. There is no triple that you can assert that says this.  However, if you were to then assert a triple with this individual using the `hasParentCompany` property, the inference engine will detect a logical contradiction.  The inference engine is telling you indirectly that there can be no `hasParentCompany` triple. Every time you try to add one, it will complain.

This is all well and good, but it is not what you want. You want to infer something is in that class by dire telepathy asserting that there is no `hasParentCompany`. There is no way to do that. Using set compliment does the opposite, but does so indirectly.

**Comment by robertmuil** [comment]
Somewhat related:
_TODO: the following comes from https://knowledgegraphconf.slack.com/archives/C018L0G51L1/p1614794346010800 but formatting lost_
I had exactly this brain-smudge when going through the chapter:
What I wanted to do was to create a class of things that have 2 wheels, and then check that instances of things with 2 wheels are of this new class, and that instances with more than 3 wheels cannot be in this class.
Seems simple, buuut when I tried to implement it...
First, the setup:
create a Class Wheel
create 3 instances of Wheel called wheel1, wheel2 and wheel3
create a Class TwoWheeledThing that is equivalent to [ hasPart exactly 2 Wheel ]
Then, I created something with two wheels, to see if it ‘conforms’ to the class:
create an instance of Thing called myBicycle
assert two object properties on it:
hasPart wheel1
hasPart wheel2
run inference, and check whether our instance is inferred to be an instance of TwoWheeledThing...
NO! It is not. Why? Because of the Open World Assumption. Who knows, thinks the inference engine, whether this Thing might have other wheels that we don’t know about?
OK, fair enough, I’d been warned a few times about that and it does make sense. So let’s go the other direction and try to tell it that something with three wheels is a TwoWheeledThing and check that it gets flagged as wrong:
create an instance of Thing called myTricycle 
assert three object properties onto myTricycle:
hasPart wheel1
hasPart wheel2
hasPart wheel3
run inference, expecting warning bells to go off, lights to flash...
NO! Everything is fine!? Here is an instance of a class that has a clear property restriction to only have 2 wheels while it clearly has 3 and yet it is NOT flagged as a contraction. WTF.
Why? Because the individuals are not disjoint! Who knows, thinks the inference engine, whether wheel1 is not actually the same individual as wheel2... or maybe all 3 of them are the same lonesome thing!
Assert the three Wheel individuals to be disjoint, and finally the inference engine complains.
This feels like my struggles with untyped languages exponentiated. It does make sense, and, I am sure, allows a high level of expressivity, but what a destroyer of ego. Felt like I hadn’t graduated high school yet.
