### ISSUE TITLE
Ch 3 section 3.1.12 pg 71 Need decipher for SPARQL query (Bob Lucas)

### ISSUE THREAD

**Issue by ghost** [KGConf/Bookclub-DemystifyingOWL#18]
SELECT ?c count(?i) WHERE {
?c rdf:type owl:Class.
?i rdf:type ?c.}

SELECT ?p count(?i) WHERE {
?p rdf:type owl:ObjectProperty.
?i ?p ?o.}
ORDER BY DESC(count(?i))  

Confused by use of ?i

**Comment by uscholdm** [comment]
This is out of the scope of this book, these were just examples of something fun to do.  But here is a brief description of what is going on. 

For the first one, the SPARQL engine finds all individuals of all classes.  If the SELECT statement was  `SELECT ?c ?i` instead of `SELECT ?c count(?i)` it would give a list of all classes and all of their individuals. However, we don't want all the individuals, we just want to know how many there are for each class. That is what the `count(?i)` is for.

The same thing is going on in the second query.  We do not want every subject of every triple used with a given property, instead we want to count up the number of triples there are that use a given property.

**Comment by ghost** [comment]
Michael,
This is the information I was asking for.
Thanks
    On Tuesday, February 16, 2021, 06:35:38 PM EST, Michael Uschold <notifications@github.com> wrote:  
 
 


This is out of the scope of this book, these were just examples of something fun to do. But here is a brief description of what is going on. For the first one, the SPARQL engine finds all individuals of all classes. If the SELECT statement was SELECT ?c ?i instead of SELECT ?c count(?i) it would give a list of all classes and all of their individuals. However, we don't want all the individuals, we just want to know how many there are for each class. That is what the count(?i) is for.

The same thing is going on in the second query. We do not want every subject of every triple used with a given property, instead we want to count up the number of triples there are that use a given property.

**Comment by dallemang** [comment]
Neither of these is good SPARQL; you can't have an aggregate (count) and a non-aggregate in the same select, unless you have a GROUP BY that tells how to link them together. 

Correct SPARQL for each of these is

SELECT ?c count(?i) WHERE {
?c rdf:type owl:Class.
?i rdf:type ?c.}
GROUP BY ?c 



SELECT ?p count(?i) WHERE {
?p rdf:type owl:ObjectProperty.
?i ?p ?o.}
GROUP BY ?p
ORDER BY DESC(count(?i))
