### ISSUE TITLE
Section 4.4 Domains and Ranges, 4.5.1 Inverse Properties (Steve Gillespie)

### ISSUE THREAD

**Issue by sgillesp-ai** [KGConf/Bookclub-DemystifyingOWL#22]
Could you comment on how object properties are used in Gist? 

**Regarding Section 4.4 Domains and Ranges:**
In Gist, the object property `Has Magnitude` has a range of the class `Magnitude`, which makes sense. No question.

But, the object property `Expressed In`—defined as “The language something was expressed in” —does not have the class `Language` as a range. Why is that? You would expect the object to be some language, by definition. Is the Skos definition too narrow? 

In Gist, the property `About ` (defined as the subject matter of a document) has a _domain_ of the class `Content`. But, `Described In` (the Inverse of `About`) does not have the _range_ of the class `Content`. Why is that? Is it because the inference engine automatically knows the range of `Described In` because it knows the domain of `About`? 

Regarding 4.5.1 Inverse Properties
On page 90, in the subsection “Explicit Inverse Properties: Yay or Nay?” it seems to discourage making inverse properties explicit. It says making inverse properties explicit carries “a cost with limited upside.” And it can “clutter up the ontology with unnecessary properties.” But, in Gist, inverse properties seem to consistently explicit. Why is that? Is it easier for the user?

**Comment by uscholdm** [comment]
> In Gist, the object property Has Magnitude has a range of the class Magnitude, which makes sense. No question.
But, the object property Expressed In—defined as “The language something was expressed in” —does not have the class Language as a range. Why is that? You would expect the object to be some language, by definition. Is the skos definition too narrow?

You raise a good point.  Recall that the criteria for using domain and range are quite strong. For the range of the property to be the class `gist:Langauge` it has to be inconceivable that something can be expressed in anything but a Language.  However, if you click the usage tab in Protege you see that a `gist:ContentExpression`  is `gist:expressedIn` a `gist:MimeType`. This tells us two thingsL
1. the range cannot be `gist:Language`, since a MimeType is not a language.
2. the `skos:definition` is indeed too narrow, as you suggested. 

Good catch.  You can go to the gist git repo and enter issues if you wish. We have an issue to go over the `skos:definition`s with a fine tooth comb.  There is a lot of room for improvement in gist definitions.

**Comment by uscholdm** [comment]
> In Gist, the property About (defined as the subject matter of a document) has a domain of the class Content. But, Described In (the Inverse of About) does not have the range of the class Content. Why is that? Is it because the inference engine automatically knows the range of Described In because it knows the domain of About?

You are correct.  This raises the question of redundancy.  If the range of a property can be inferred from the domain of its inverse, it is redundant to have both.   Redundancy is often a bad idea, because it clutters things up, and if there is a change then that change has to be updated in more than one place. If left up to inference, a change in the domain of a property will be automatically reflected in the range of its inverse.   There are times when leaving redundancies in the ontology helps to reduce errors.  One example is the transitivity of import. If ontology A depends on ontologies B, C and D and if B imports C and D, then then it is not necessary to state that A imports C or D.  But what if you manage ontology A but not B, and someone changes B so that it no longer imports D. Now you have a maintenance problem. You will have to manually add a triple saying that A imports D.  This could easily be forgotten. So it is good practice to add redundant import triples for this reason.

In the case of the domain, range, inverse property example, that does not arise.

**Comment by uscholdm** [comment]
> On page 90, in the subsection “Explicit Inverse Properties: Yay or Nay?” it seems to discourage making inverse properties explicit. It says making inverse properties explicit carries “a cost with limited upside.” And it can “clutter up the ontology with unnecessary properties.” But, in Gist, inverse properties seem to consistently explicit. Why is that? Is it easier for the user?

I'm not sure what you mean.  Only 21 of the 108 gist object properties have explicit inverses.  The inverse of any property is always 'there' in the sense that you can always refer to it using the `owl:inverseOf` construct.

**Comment by sgillesp-ai** [comment]
Thanks for your very helpful and patient replies. I should have written "properties seem to be **frequently** explicit". There are 20 or so explicit pairs of inverses. I get your point, though: the remaining 60 or so object properties have implicit inverses, reducing clutter. 

> > On page 90, in the subsection “Explicit Inverse Properties: Yay or Nay?” it seems to discourage making inverse properties explicit. It says making inverse properties explicit carries “a cost with limited upside.” And it can “clutter up the ontology with unnecessary properties.” But, in Gist, inverse properties seem to be `**consistently** `explicit. Why is that? Is it easier for the user?
> 
> I'm not sure what you mean. Only 21 of the 108 gist object properties have explicit inverses. The inverse of any property is always 'there' in the sense that you can always refer to it using the `owl:inverseOf` construct.
