### ISSUE TITLE
Section 4.4 Domain and Range

### ISSUE THREAD

**Issue by lrumanes** [KGConf/Bookclub-DemystifyingOWL#23]
Suppose I want to say an individual can only give birth to another in the same species.  I want to define a **givesBirthTo** property with a range of the species of the subject, so an instance with a species of **Human** can only give birth to humans.  How could you model this in OWL without making every property species-specific and having them look like **humanGivesBirthTo**?

**Comment by uscholdm** [comment]
This is a very good question. Unfortunately, you cannot do it. We will explore in chapter 7 some of the limitations of OWL. But let's look at this example for now and start out with what we can do.  We will be introducing a new kind of restriction. 

What you want to say in OWLesque English is that"
- Every instance of Human is also an instance of the set of all things that can give birth to only Humans.

What this looks like in a Manchester-like syntax is"
- `Human subClassOf (givesBirthTo only Human)`
-  This is an example of an `allValuesFrom` (universal) restriction. This is explained in section 5.4.4.

This is fine, but this is exactly what you do not want to have to do for every species, for example: 
- `Elephant subClassOf (givesBirthTo only Elephant)`
- `Amoeba subClassOf (givesBirthTo only Amoeba )`
- `KingPenguin subClassOf (givesBirthTo only KingPenguin )`


You want to be able to say that for every class `C` that is a subclass of say `Animal`
- `C subClassOf (givesBirthTo only C)`

You cannot do that. This is explained in section 7.4.

**Comment by dallemang** [comment]
I posed this question many years ago to some of the OWL designers, in the context of currencies; instead of species, we had currencies.  FIBO is aware of 158 different currencies; we wanted to define the notion of a "single currency swap", where the two legs trade in the same currency (and a "cross-currency swap" the relative complement of that).   The recommendation was indeed to generate 158 different restrictions and then UNION them together.  In response to the (I thought, obvious) question, "what happens when I learn about a new currency?" the answer was to build some infrastructure around the model that would update it automatically when we learned of new currencies.    When Mike says, "this is exactly what you do not want to do", he couldn't be more right; this undermines the whole point of having a formal, intentional model.

**Comment by kmcorbett** [comment]
This heuristic "an individual can only give birth to another in the same species" is a great example of how and when to leverage a general purpose inferencing language to extend reasoning beyond the model. OWL/DL and description logics in general can't represent all the rules in "the world". A rules engine such as ReactiveCore converts OWL/DL to its native rules language, then you can blend in application logic rules. 

This begs the next question: what happens when data (triples) are introduced that "violate" the rules? With that I'll invite anyone interested to post questions or comments in KGC Slack on [#topic-rulesbasedkg](https://knowledgegraphconf.slack.com/archives/C01HYKP9PHN) a low traffic discussion of rules-based systems with knowledge graphs

**Comment by dallemang** [comment]
I wrote a blog entry on this topic, ten years ago!  https://dallemang.typepad.com/my_weblog/2010/08/extending-owl-rl-.html#comments  
 
I like the idea of ReactiveCore automatically converting OWL into rules; that's one step beyond what we were doing back in 2010.

**Comment by lrumanes** [comment]
I keep trying to respond to this concisely without going down a rabbit hole, and all of the sudden there's a sentence on procedural attachment, and ontology-oriented programming, and a paragraph on prolog.  So I'll move to [ #topic-rulesbasedkg](https://knowledgegraphconf.slack.com/archives/C01HYKP9PHN).
