### ISSUE TITLE
Chapter 5: Why are there (almost) no mechanisms to 'close' parts of the OWL world?

### ISSUE THREAD

**Issue by Robert-Muil** [KGConf/Bookclub-DemystifyingOWL#31]
We have enumerations (oneOf) which are closed. Why is it not possible to define, for example, that a class's subclasses span the whole class (e.g. define a Thing as having Mineral and Animal subclasses, and declaring those to be the only two Things that exist )?

**Comment by uscholdm** [comment]
> Why is it not possible to define, for example, that a class's subclasses span the whole class (e.g. define a Thing as having Mineral and Animal subclasses, and declaring those to be the only two Things that exist )?

OWL is inherently open world. Open means something might be true, even if it is not asserted. So, closing the world always entails saying something about what is NOT true.  There are a handful of OWL constructs that allow you to close the world.  

- `oneOf` says there are NO other members of the class except those named
- `owl:intersectionOf` means NO other instance can be in the class unless it is in _both_ other classes
- `owl:unionOf` means NO other instance can be in the class unless it is in _at least one_ of the classes. This will solve the problem as stated with the animal and mineral example.
- `owl:disjointUnionOf` let's you say even more about the Animal and Mineral classes, since they are disjoint.  It is used if you want to partition a class into subclasses that are pairwise disjoint and their union is equal to the initial class. This is covered in chapter 8.
- `disjointWith`  says there are NO instances in common between two classes.
- `owl:complementOf` says that instances of a given class are NOT members of the complement class.

**Comment by Robert-Muil** [comment]
Superb, I'll investigate these: thank you kindly Michael, exactly what I was asking for.
