### ISSUE TITLE
Chapter 2 pg 37 & pg 47(Bob Lucas)

### ISSUE THREAD

**Issue by ghost** [KGConf/Bookclub-DemystifyingOWL#6]
Pg 37 Confused about logic flow where John Doe as an individual gets introduced to become _PatientJohnDoe

Pg 47 2.4.4 Confused: Set Union - plain english description "Set Union here means logical "and".
                                   Set Intersection - "Set intersection here means logical "and".  
     Shouldn't Set Union be a logical "or"

Minor typos:
pg 45 mid page under Create an individual and give a type
             Types: (Should read Type - no "s")
                 Person

pg 45 2.4.3 Properties 

Property: A property is a way to relate individuals to each other or "two" literals. should read "to"

**Comment by uscholdm** [comment]
> Pg 47 2.4.4 Confused: Set Union - plain english description "Set Union here means logical "and".
Set Intersection - "Set intersection here means logical "and".
Shouldn't Set Union be a logical "or"

Yes it should, good catch.

**Comment by uscholdm** [comment]
> Minor typos:
pg 45 mid page under Create an individual and give a type
Types: (Should read Type - no "s")
Person

I believe this is correct Manchester Syntax.  It assumes the could be more than one, but does not detect the case for only one and use the singular form. Note that it says `Annotations` even though there is only one.

**Comment by uscholdm** [comment]
> pg 45 2.4.3 Properties
Property: A property is a way to relate individuals to each other or "two" literals. should read "to"

Good catch, thank you.

**Comment by uscholdm** [comment]
> Pg 37 Confused about logic flow where John Doe as an individual gets introduced to become _PatientJohnDoe

We met John Doe in Chapter 1. On p5 he was an instance of Cancer Patient.  Figure 1.5 on p9 shows that Cancer Patient is a kind of Patient which, in turn, is a kind of Person.  Choosing an IRI for the individual should be done with care.  In chapter 2, I chose an IRI to suggest hew was a patient.   It is important to create and follow conventions for minting IRIs. If I had to do it over again, I would probably use :`_PersonJohnDoe`, since he is fundamentally a person. He is inferred to be a patient because he want to the doctor.
